from setuptools import setup, find_packages

setup(
    name='scientific-image-analyzer',
    version='1.0.0',
    author='Scientific Computing Team',
    description='Multi-dimensional microscopy image analysis suite',
    packages=find_packages(),
    py_modules=[
        "advanced_analysis",
        "batch_processor",
        "fibsem_plugins",
        "file_io_napari",
        "laminAmutants",
        "main",
        "main_napari",
        "scientific_analyzer",
        "simple_analyzer",
        "tif_diagnostic",
        "timelapse_processor",
    ],
    # By using include_package_data=True and a MANIFEST.in file,
    # we ensure that non-Python files like napari.yaml are included.
    include_package_data=True,
    install_requires=[
        'napari[all]',
        'PyQt6>=6.4.0',
        'PyQt6-Qt6>=6.4.0',
        'qtpy>=2.3.0',
        'magicgui>=0.5.0',
        'numpy>=1.21.0',
        'scipy>=1.9.0',
        'scikit-image>=0.19.0',
        'matplotlib>=3.5.0',
        'pandas>=1.5.0',
        'aicsimageio>=4.9.4',
        'tifffile>=2023.3.15',
        'imagecodecs>=2023.7.10',
        'imageio>=2.25.0',
        'Pillow>=9.0.0',
        'h5py>=3.7.0',
        'zarr>=2.13.0',
        'dask>=2023.1.0',
        'napari-plugin-engine>=0.2.0',
        'napari-svg>=0.2.1',
        'npe2>=0.7.9',
        'Flask>=2.3.0',
        'Werkzeug>=2.3.0',
        'requests>=2.28.0',
        'mrcfile>=1.4.0',
        'opencv-python>=4.7.0',
        'numpydoc>=1.9.0',
        'ome-types>=0.6.2',
        'ome-zarr>=0.10.2',
        'console>=0.1.4',
    ],
    entry_points={
        'napari.manifest': [
            'scientific-image-analyzer = pymaris_napari:napari.yaml',
        ],
    },
)
